### ISSUE TITLE
cannot get catalog info, and cannot get mainnet nft info

### ISSUE THREAD

**Issue by syw-zj** [dapperlabs/nft-catalog#103]
the code is:
```
const addressMap = await flowCatalog.getAddressMaps();
    const catalog = await flowCatalog.scripts.getNftCatalog(addressMap);
    console.log(catalog);
```
the result is:
```
[
  null,
  HTTPRequestError [HTTP Request Error]:
        HTTP Request Error: An error occurred when interacting with the Access API.
        error=Invalid Flow argument: failed to execute the script on the execution node execution-5f6c73a22445d7d958c6a37c1f3be99c72cacd39894a3e46d6647a9adb007b4d@execution-001.devn
et38.nodes.onflow.org:3569=100: rpc error: code = InvalidArgument desc = failed to execute script: failed to execute script at block (3c0d1eef596167778723c5d746b98882273683f77687026
94cd2ede2c2d71842): [Error Code: 1106] error caused by: [Error Code: 1101] cadence runtime error: Execution failed:
  error: internal error: get program failed: cannot check account freeze status: failed to load account status for the account (e666c53e1758dec6): [Error Code: 1106] max interaction
 with storage has exceeded the limit (used: 20577720 bytes, limit 20000000 bytes)
  goroutine 1795848883 [running]:
  runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
  github.com/onflow/cadence/runtime/err ... 3 +0xcfe
  google.golang.org/grpc.(*Server).handleStream(0xd3932eaa80, {0x2813f40, 0xd439561860}, 0xd3d31837a0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:1620 +0xa2f
  google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:922 +0x98
  created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:920 +0x28a

  --> 9083cbc90646dfd00b4ea79eca542ef1aa86149b8b0b720a3e6ed878ec26a9d2

        hostname=https://rest-testnet.onflow.org
        path=/v1/scripts?block_height=sealed
        method=POST
        requestBody={"script":"CmltcG9ydCBORlRDYXRhbG9nIGZyb20gMHgzMjRjMzRlMWM1MTdlNGRiCgpwdWIgZnVuIG1haW4oKToge1N0cmluZyA6IE5GVENhdGFsb2cuTkZUQ2F0YWxvZ01ldGFkYXRhfSB7CiAgICByZXR1cm
4gTkZUQ2F0YWxvZy5nZXRDYXRhbG9nKCkKfQo=","arguments":[]}
        responseBody={"code":400,"message":"Invalid Flow argument: failed to execute the script on the execution node execution-5f6c73a22445d7d958c6a37c1f3be99c72cacd39894a3e46d6647
a9adb007b4d@execution-001.devnet38.nodes.onflow.org:3569=100: rpc error: code = InvalidArgument desc = failed to execute script: failed to execute script at block (3c0d1eef596167778
723c5d746b98882273683f7768702694cd2ede2c2d71842): [Error Code: 1106] error caused by: [Error Code: 1101] cadence runtime error: Execution failed:\nerror: internal error: get program
 failed: cannot check account freeze status: failed to load account status for the account (e666c53e1758dec6): [Error Code: 1106] max interaction with storage has exceeded the limit
 (used: 20577720 bytes, limit 20000000 bytes)\ngoroutine 1795848883 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/onflow/cadence
/runtime/err ... 3 +0xcfe\ngoogle.golang.org/grpc.(*Server).handleStream(0xd3932eaa80, {0x2813f40, 0xd439561860}, 0xd3d31837a0, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.2/se
rver.go:1620 +0xa2f\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2()\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:922 +0x98\ncreated by google.golang.org/grpc.(*S
erver).serveStreams.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:920 +0x28a\n\n--> 9083cbc90646dfd00b4ea79eca542ef1aa86149b8b0b720a3e6ed878ec26a9d2\n"}
        responseStatusText=Bad Request
        statusCode=400

      at _callee$ (webpack://flowCatalog/./node_modules/@onflow/transport-http/dist/sdk-send-http.module.js?:146:33)
      at tryCatch (webpack://flowCatalog/./node_modules/@babel/runtime/helpers/regeneratorRuntime.js?:86:17)
      at Generator.eval [as _invoke] (webpack://flowCatalog/./node_modules/@babel/runtime/helpers/regeneratorRuntime.js?:66:24)
      at Generator.eval [as next] (webpack://flowCatalog/./node_modules/@babel/runtime/helpers/regeneratorRuntime.js?:117:21)
      at asyncGeneratorStep (webpack://flowCatalog/./node_modules/@babel/runtime/helpers/asyncToGenerator.js?:3:24)
      at _next (webpack://flowCatalog/./node_modules/@babel/runtime/helpers/asyncToGenerator.js?:25:9)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    statusCode: 400,
    errorMessage: 'Invalid Flow argument: failed to execute the script on the execution node execution-5f6c73a22445d7d958c6a37c1f3be99c72cacd39894a3e46d6647a9adb007b4d@execution-001
.devnet38.nodes.onflow.org:3569=100: rpc error: code = InvalidArgument desc = failed to execute script: failed to execute script at block (3c0d1eef596167778723c5d746b98882273683f776
8702694cd2ede2c2d71842): [Error Code: 1106] error caused by: [Error Code: 1101] cadence runtime error: Execution failed:\n' +
      'error: internal error: get program failed: cannot check account freeze status: failed to load account status for the account (e666c53e1758dec6): [Error Code: 1106] max intera
ction with storage has exceeded the limit (used: 20577720 bytes, limit 20000000 bytes)\n' +
      'goroutine 1795848883 [running]:\n' +
      'runtime/debug.Stack()\n' +
      '\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\n' +
      'github.com/onflow/cadence/runtime/err ... 3 +0xcfe\n' +
      'google.golang.org/grpc.(*Server).handleStream(0xd3932eaa80, {0x2813f40, 0xd439561860}, 0xd3d31837a0, 0x0)\n' +
      '\t/go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:1620 +0xa2f\n' +
      'google.golang.org/grpc.(*Server).serveStreams.func1.2()\n' +
      '\t/go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:922 +0x98\n' +
      'created by google.golang.org/grpc.(*Server).serveStreams.func1\n' +
      '\t/go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:920 +0x28a\n' +
      '\n' +
      '--> 9083cbc90646dfd00b4ea79eca542ef1aa86149b8b0b720a3e6ed878ec26a9d2\n'
  }
]
```

**Comment by syw-zj** [comment]
and I cannot get nft info at mainnet. `const counts = await flowCatalog.scripts.getNftsCountInAccount({addressMap, args: ["0xd48b5e642ec788aa"]});` doesn't return any info but only return `[Error Code: 1201] error caused by: fatal error: storage error: storage address allocation failed: [Error Code: 1201] account not found for address d48b5e642ec788aa`
